#!/bin/bash

if [ "$EUID" -ne 0 ]
	then echo "Not runned as sudo"
	exit 1;
fi

if [ -n "$1" ]; then 
if [[ $1 = "-t" ]]; then 

	case $2 in 
	A ) 
	echo "$3			IN	A	$4" >> /etc/bind/zones/db."$5"
	DB="/etc/bind/zones/db.$5"
	;;
	MX )
	echo "@			IN	MX	10	$3.$5." >> /etc/bind/zones/db."$5"
	echo "$3			IN	A	$4" >> /etc/bind/zones/db."$5"
	DB="/etc/bind/zones/db.$5"
	;;
	CNAME )
	DB="/etc/bind/zones/db.$4"
	echo "$3			IN 	CNAME	$4." >> "$DB"
	;;
	esac
	else
	echo "$1			IN	A	$2" >> /etc/bind/zones/db. "$3"
	DB="/etc/bind/zones/db.$3"
	fi


	serialline=$(grep "Serial" "$DB")
	serialnumber=$(echo $serialline | cut -d\; -f 1)
	((serialnumber++))
	newserial="$serialnumber	; Serial werkt"
	echo $newserial;
	sed -i "s/.*Serial.*/\t\t\t	$newserial/g" "$DB"

	rndc reload
	systemctl restart bind9

else 
	echo "error: try dns_add_record -t A test 101.101.101.101 zonessss.gleb-shalabotov.sb.uclllabs.be"
fi
