#!/bin/bash

if [ "$EUID" -ne 0]
	then echo "Not runned as sudo"
	exit 1;
fi

if [-n "$1" ]; then 
if [[ $1 = "-t" ]]; then 

	case $2 in 
	A ) 
	echo -e "$3			IN	A	$4" >> /etc/bind/zones/db."$5"
	DB="etc/bind/zones/db.$5"
	;;
	MX )
	echo -e "@			IN	MX	10	$3.$5." >> etc/bind/zones/db."$5"
	echo -e "$3			IN	A	$4" >> /etc/bind/zones/db."$5"
	DB="/etc/bind/zones/db.$5"
	;;
